name: Release

on:
  push:
    tags:
      - '*'

env:
  NIMVER: "2.0.x"

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            name: linux
          - os: windows-latest
            name: windows
          - os: macOS-latest
            name: macos
    steps:
    - uses: actions/checkout@v4
    - uses: jiro4989/setup-nim-action@3a60cf06f20c1cf3a9becf76b30288c0361d5f1e  # v2
      with:
        nim-version: ${{ env.NIMVER }}
        repo-token: ${{ secrets.GITHUB_TOKEN }}

    - name: Compile (Linux and Windows)
      run: nimble build -d:release
      if: matrix.name != 'macos'

    - name: Compile (macOS)
      if: matrix.name == 'macos'
      run: ./scripts/build_release_macos.sh

    - name: Compile libnwnscriptcomp (all platforms)
      run: nimble build_libnwnscriptcomp

    - name: Create zip archive (Linux and macOS)
      if: matrix.name != 'windows'
      shell: bash
      run: |
        cd bin
        zip -r ../neverwinter-${{ matrix.name }}.zip *
        cd ..

    - name: Create zip archive (Windows)
      if: matrix.name == 'windows'
      shell: pwsh
      run: |
        Compress-Archive -Path "bin\*" -DestinationPath "neverwinter-${{ matrix.name }}.zip"

    - uses: actions/upload-artifact@v4
      with:
        name: neverwinter-${{ matrix.name }}.zip
        path: neverwinter-${{ matrix.name }}.zip

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: .
          merge-multiple: true
      - run: ls -R
      - name: Create Release
        uses: softprops/action-gh-release@da05d552573ad5aba039eaac05058a918a7bf631
        with:
          files: |
            *.zip
          draft: true
          name: ${{ github.ref_name }}
